name: Web BFF Core CI

on:
  push:
    paths:
      - "packages/web-bff-core/**"
      - ".github/workflows/web-bff-core-ci.yml"
  pull_request:
    paths:
      - "packages/web-bff-core/**"
      - ".github/workflows/web-bff-core-ci.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/web-bff-core

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"

      - name: Install
        env:
          npm_config_ignore_scripts: "true"
        run: npm install --no-audit --no-fund

      - name: Typecheck
        run: npm run typecheck

      - name: Tests
        run: npm test
